// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JwtWork.PISDB.Models;

public partial class PSJob
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string JobNo { get; set; }

    [StringLength(50)]
    public string FolderName { get; set; }

    [Required]
    [StringLength(255)]
    public string JobTitle { get; set; }

    [StringLength(500)]
    public string StructureNo { get; set; }

    [StringLength(50)]
    public string ContractNo { get; set; }

    [StringLength(50)]
    public string FileNo { get; set; }

    [StringLength(50)]
    public string ProjNo { get; set; }

    [Column(TypeName = "decimal(18, 3)")]
    public decimal? MeterSpanLen { get; set; }

    [StringLength(50)]
    public string StructureType { get; set; }

    public string MapHtml { get; set; }

    public int? CompleteYear { get; set; }

    public string ThumbnailFile { get; set; }

    public string MapFile { get; set; }

    [StringLength(500)]
    public string Remark { get; set; }

    public bool NoCopyNeeded { get; set; }

    public bool Disabled { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [StringLength(50)]
    public string UpdatedBy { get; set; }

    [InverseProperty("PSJob")]
    public virtual ICollection<PSItem> PSItem { get; set; } = new List<PSItem>();
}