// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace JwtWork.SQLDB.Models;

public partial class JWTWORKContext : DbContext
{
    public JWTWORKContext()
    {
    }

    public JWTWORKContext(DbContextOptions<JWTWORKContext> options)
        : base(options)
    {
    }

    public virtual DbSet<UserTB> UserTB { get; set; }

    

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<UserTB>(entity =>
        {
            entity.Property(e => e.LoginAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}